//! Golden tests: the Rust ports in `silero_native::chunking` must reproduce
//! `ttsd/ttsd/chunking.py` output exactly.
//!
//! Fixtures are generated by `tmp/gen_chunking_fixtures.py` from the actual
//! ttsd code — regenerate them if the ttsd reference changes.

use std::collections::HashSet;

use serde::Deserialize;
use silero_native::chunking::{sanitize_for_silero, split_into_chunks};
use silero_native::frontend::text::prepare_text_input;

#[derive(Deserialize)]
struct SanitizeFixtures {
    cases: Vec<SanitizeCase>,
}

#[derive(Deserialize)]
struct SanitizeCase {
    input: String,
    output: String,
}

#[test]
fn sanitize_matches_ttsd_golden() {
    let raw = include_str!("fixtures/chunking/sanitize.json");
    let fixtures: SanitizeFixtures = serde_json::from_str(raw).expect("fixture JSON must parse");
    for case in &fixtures.cases {
        assert_eq!(
            sanitize_for_silero(&case.input),
            case.output,
            "sanitize mismatch for input {:?}",
            case.input
        );
    }
}

/// Regression guard for the review finding: a newline between words must
/// survive the native frontend as a word separator (the symbol filter drops
/// `\n` itself, so the sanitize step must turn it into a space first).
#[test]
fn multiline_words_are_not_glued_after_sanitize() {
    // symbols[3:] of the v5_ru bundle frontend.json
    let symbols_tail: HashSet<char> = "!+,-.:;?абвгдежзийклмнопрстуфхцчшщъыьэюяё–… "
        .chars()
        .collect();
    let sanitized = sanitize_for_silero("строки\nновая");
    let out = prepare_text_input(&sanitized, &symbols_tail);
    assert_eq!(out.sentence, "строки новая");
}

#[derive(Deserialize)]
struct SplitFixtures {
    max_chunk_size: usize,
    cases: Vec<SplitCase>,
}

#[derive(Deserialize)]
struct SplitCase {
    input: String,
    chunks: Vec<(String, usize)>,
}

#[test]
fn split_matches_ttsd_golden() {
    let raw = include_str!("fixtures/chunking/split.json");
    let fixtures: SplitFixtures = serde_json::from_str(raw).expect("fixture JSON must parse");
    assert_eq!(
        silero_native::chunking::MAX_CHUNK_SIZE,
        fixtures.max_chunk_size,
        "MAX_CHUNK_SIZE drifted from ttsd"
    );
    for case in &fixtures.cases {
        assert_eq!(
            split_into_chunks(&case.input),
            case.chunks,
            "split mismatch for input of {} chars",
            case.input.chars().count()
        );
    }
}
