//! Golden parity suite: the full Rust engine must reproduce the Python ONNX
//! pipeline output on a fixed phrase set (tech text, numbers, homographs, ё,
//! punctuation, long sentences, single words, explicit stress markers).
//!
//! Reference waveforms are generated by the Python ONNX pipeline (same
//! onnxruntime the engine links against), not torch `apply_tts`: the
//! torch-vs-ONNX float drift reaches ~4e-3 on some phrases and is already
//! pinned by the exporter self-check on its own phrase set — this suite pins
//! the Rust engine against the bundle it ships. The drift measured at
//! generation time is recorded per case as `torch_max_abs_diff`.
//!
//! Per case the test pins three things:
//!   1. `spoken_text` (accented frontend output) matches the torch frontend
//!      symbol-for-symbol;
//!   2. waveform max abs diff vs the int16 reference ≤ 1e-3 (the int16
//!      quantization itself costs at most ~3e-5, well inside the budget);
//!   3. sample count matches within ±1 output frame (600 samples at 48 kHz,
//!      scaled by rate).
//!
//! Fixtures come from `tests/tools/gen_parity_fixtures.py` (real v5_ru model,
//! references taken after `unpack_q_model`; regenerate via
//! `tests/tools/regenerate_fixtures.sh`). Bundle-gated like the other
//! integration tests: these run locally / wherever the ~230 MB bundle is
//! present (`SILERO_NATIVE_BUNDLE` or the default `tmp/bundle-v5`); on CI
//! machines without the bundle the test skips and only the unit tests run.

use std::path::PathBuf;

use serde::Deserialize;
use silero_native::engine::Engine;

mod common;

const WAV_TOL: f32 = 1e-3;

#[derive(Deserialize)]
struct FixtureFile {
    cases: Vec<FixtureCase>,
}

#[derive(Deserialize)]
struct FixtureCase {
    id: String,
    input: String,
    speaker: String,
    sample_rate: u32,
    spoken_text: String,
    wav: String,
    samples: usize,
    /// torch-vs-ONNX drift measured at fixture generation (informational).
    torch_max_abs_diff: f32,
}

/// Decode an int16 mono WAV fixture back to f32 in [-1, 1].
fn read_wav(path: &std::path::Path) -> Vec<f32> {
    let mut reader = hound::WavReader::open(path)
        .unwrap_or_else(|e| panic!("cannot open {}: {e}", path.display()));
    reader
        .samples::<i16>()
        .map(|s| s.expect("valid int16 sample") as f32 / 32767.0)
        .collect()
}

/// One output frame at the given rate (hop 600 at the native 48 kHz).
fn frame_len(sample_rate: u32) -> usize {
    600 * sample_rate as usize / 48000
}

#[test]
fn engine_output_matches_torch_apply_tts_golden() {
    let Some(dir) = common::gated_bundle_dir() else {
        return;
    };
    let engine = Engine::load(&dir).expect("bundle must load");

    let raw = include_str!("fixtures/parity/parity.json");
    let fixtures: FixtureFile = serde_json::from_str(raw).expect("fixture JSON must parse");
    let fixture_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/parity");

    let mut worst_diff = 0.0f32;
    let mut worst_id = String::new();
    let mut worst_torch = 0.0f32;
    for case in &fixtures.cases {
        let out = engine
            .synthesize(&case.input, &case.speaker, case.sample_rate)
            .unwrap_or_else(|e| panic!("synthesis failed for {}: {e}", case.id));

        assert_eq!(
            out.spoken_text, case.spoken_text,
            "spoken_text mismatch for {}",
            case.id
        );

        let len_diff = out.samples.len().abs_diff(case.samples);
        assert!(
            len_diff <= frame_len(case.sample_rate),
            "length mismatch for {}: engine {} vs reference {} (diff {len_diff} > 1 frame)",
            case.id,
            out.samples.len(),
            case.samples
        );

        let reference = read_wav(&fixture_dir.join(&case.wav));
        let n = out.samples.len().min(reference.len());
        let max_diff = out.samples[..n]
            .iter()
            .zip(&reference[..n])
            .map(|(a, b)| (a - b).abs())
            .fold(0.0f32, f32::max);
        assert!(
            max_diff <= WAV_TOL,
            "waveform mismatch for {}: max abs diff {max_diff:.3e} > {WAV_TOL}",
            case.id
        );
        if max_diff > worst_diff {
            worst_diff = max_diff;
            worst_id = format!("{} ({}, {} Hz)", case.id, case.speaker, case.sample_rate);
        }
        worst_torch = worst_torch.max(case.torch_max_abs_diff);
    }
    eprintln!(
        "parity: {} cases passed, worst max abs diff {worst_diff:.3e} on {worst_id} \
         (worst recorded torch-vs-ONNX drift {worst_torch:.3e})",
        fixtures.cases.len()
    );
}
